#!/bin/sh
# A little shell script for removing MacOS .DS_Store file(s) 
#
# Copyright (c) 2009 Richard Sentino

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Revision History
#  Version 1.0 
#   Initial Release
#  
# Last Updated : 28-July-2009 

FIND_CMD="find"
FIND_SWITCHES="-type f -name .DS_Store -print0"
XARGS="xargs -0 rm -fv"

if [ $# -lt 1 ]; then
	echo "Usage: dstorex <path/to/directory>"
	echo "Please specify a directory".
	exit 1
fi

DSTOREX="$FIND_CMD $1 $FIND_SWITCHES"

# start removing .DS_Store files 
echo "dstorex 1.0 by Richard Sentino"
echo ""
echo "removing .DS_Store file(s)..."
$DSTOREX | $XARGS
echo "done."

exit 0